# Build Lambda Layer for Python
trigger:
  branches:
    include:
    - dev/*
    - main
    - prod/*
  paths:
    include:
    - '${__PROJECTNAME__}/*'

# when this stack should be triggered by another project (usually a lambda layer)
# resources:
#   pipelines:
#     - pipeline: 'referred-pipeline'
#       project: '${__PROJECTNAME__}/*'
#       source: 'referred-pipeline'
#       trigger:
#         branches:
#         - dev/*
#         - main
#         - prod/*

variables:
- template: /environments.yml
- name: tag
  value: '$(Build.BuildId)'
- name: project
  value: '${__PROJECTNAME__}'
- name: repository
  value: 'local-builder-image-repository'

pool:
  vmImage: 'ubuntu-latest'
steps:
- script: |
    rm -rf $(project)/dist
    mkdir $(project)/dist
  displayName: Copy Zip File from Image Instance to to Local
- task: Docker@2
  displayName: Use Lamdba Image to Build Layer
  inputs:
    command: build
    dockerfile: '$(project)/layer.dockerfile'
    repository: $(repository)
    tags: latest
- script: |
    /usr/bin/docker run --name $(repository)-instance $(repository):latest
    /usr/bin/docker cp $(repository)-instance:/var/task/layer.zip $(project)/dist/
    docker rm -f $(repository)-instance
    cp $(project)/cloudformation.yml $(project)/dist/
  displayName: Copy Zip File from Image Instance to to Local
- task: S3Upload@1
  displayName: Upload Layzer File to Artifacts Bucket
  inputs:
    awsCredentials: '$(AWSAccountId)'
    regionName: '$(AWSRegion)'
    bucketName: '$(AWSAccountId)-$(AWSRegion)-stacks'
    createBucket: true
    sourceFolder: '$(project)/dist'
    globExpressions: '**'
    targetFolder: '$(Application)/$(EnvironmentTarget)/$(Version)/$(project)/$(Build.BuildId)'
- task: LambdaInvokeFunction@1
  continueOnError: true
  displayName: Check the state of CloudFormation
  inputs:
    awsCredentials: '$(AWSAccountId)'
    regionName: '$(AWSRegion)'
    functionName: 'aws-devops-helper'
    payload: |
      {
        "name": "$(Application)--$(project)--$(AWSRegion)--$(EnvironmentTarget)",
        "query": "CloudFormationState"
      }
    outputVariable: 'ShouldDeleteStack'
- task: CloudFormationDeleteStack@1
  continueOnError: true
  displayName: Delete the CloudFormation when necessary
  condition: eq(variables.ShouldDeleteStack , '"true"')
  inputs:
    awsCredentials: '$(AWSAccountId)'
    regionName: '$(AWSRegion)'
    stackName: '$(Application)--$(project)--$(AWSRegion)--$(EnvironmentTarget)'
- task: CloudFormationCreateOrUpdateStack@1
  displayName: Run the CloudFormation Create/Update
  inputs:
    awsCredentials: '$(AWSAccountId)'
    regionName: '$(AWSRegion)'
    stackName: '$(Application)--$(project)--$(AWSRegion)--$(EnvironmentTarget)'
    templateSource: 's3'
    s3BucketName: '$(AWSAccountId)-$(AWSRegion)-stacks'
    s3ObjectKey: '$(Application)/$(EnvironmentTarget)/$(Version)/$(project)/$(Build.BuildId)/cloudformation.yml'
    templateParametersSource: 'inline'
    templateParameters: |
      [
        {"ParameterKey":"AWSAccountId", "ParameterValue":"$(AWSAccountId)"},
        {"ParameterKey":"AWSRegion", "ParameterValue":"$(AWSRegion)"},
        {"ParameterKey":"Application", "ParameterValue":"$(Application)"},
        {"ParameterKey":"Version", "ParameterValue":"$(Version)"},
        {"ParameterKey":"Project", "ParameterValue":"$(project)"},
        {"ParameterKey":"EnvironmentTarget", "ParameterValue":"$(EnvironmentTarget)"},
        {"ParameterKey":"Runtime", "ParameterValue":"$(LambdaRuntimePython)"},
        {"ParameterKey":"BuildId", "ParameterValue":"$(Build.BuildId)"}
      ]
    capabilityAutoExpand: true
