# define the variables that will be shared across all pipelines
# use following syntax to import
# variables
# - template: /environments.yml

variables:
  # shared variables:
  Application: ${__APPLICATIONNAME__}
  Version: 1.0.0
  LambdaRuntimeDotNetCore: dotnetcore3.1
  LambdaRuntimeNodeJS: nodejs12.x
  LambdaRuntimePython: python3.8
  
  # conditional variables:
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/dev/') }}:
    EnvironmentTarget: dev
    AWSAccountId: '${__ACCOUNTID__}'
    AWSRegion: ${__REGION__}
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    EnvironmentTarget: staging
    AWSAccountId: '${__ACCOUNTID__}'
    AWSRegion: ${__REGION__}

  # create 
  # ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/prod/${__ACCOUNTID__}-${__REGION__}') }}:
  #   EnvironmentTarget: prod
  #   AWSAccountId: ${__ACCOUNTID__}
  #   AWSRegion: ${__REGION__}
